name: Code style checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: run code checkers
      env:
        JDBI_MAVEN_OPTS: "-DskipTests=true -B -fae"
      run: |
        ./mvnw --version
        echo $PATH
        make install
