---
name: Test Guava versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  guava:
    name: Test Guava versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 33.0.0-jre, 32.1.3-jre, 32.0.1-jre, 31.1-jre ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        env:
          MAVEN_CONFIG: "-B -fae"
        run: |
          make install-fast

      - name: Test
        env:
          MAVEN_CONFIG: "-B -fae -Ddep.guava.version=${{ matrix.test-version }}"
        run: |
          make run-tests
